services:
  - type: web
    name: xade-wallet-service
    runtime: node
    buildCommand: npm install
    startCommand: npm run start:prod
    envVars:
      - key: NODE_ENV
        value: production
      - key: AWS_REGION
        sync: false
      - key: CROSSMINT_API_KEY
        sync: false
      - key: ADMIN_WALLET_ADDRESS
        sync: false
      - key: DELEGATED_KEY_PRIVATE_KEY
        sync: false
      - key: DELEGATED_KEY_ADDRESS
        sync: false
      - key: WALLET_ADDRESS
        sync: false
      - key: KMS_KEY_ID
        sync: false
      - key: KMS_KEY_ARN
        sync: false
      - key: KEYS_TABLE_NAME
        sync: false
      - key: ALLOWED_ORIGINS
        sync: false
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
      - key: SUPABASE_WALLETS_TABLE
        sync: false 